// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace csharpMcp.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("SauceDemo Order Flow")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class SauceDemoOrderFlowFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "tests/Features", "SauceDemo Order Flow", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "SauceDemoOrder.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("tests/Features/SauceDemoOrder.feature.ndjson", 3);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Add five products to cart and complete checkout with verification")]
        public async global::System.Threading.Tasks.Task AddFiveProductsToCartAndCompleteCheckoutWithVerification()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Add five products to cart and complete checkout with verification", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 3
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
    await testRunner.GivenAsync("I navigate to SauceDemo login page \"https://www.saucedemo.com/?utm_source=chatgpt" +
                        ".com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 5
    await testRunner.WhenAsync("I log in with username \"standard_user\" and password \"secret_sauce\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "ProductName"});
                table1.AddRow(new string[] {
                            "Sauce Labs Backpack"});
                table1.AddRow(new string[] {
                            "Sauce Labs Bike Light"});
                table1.AddRow(new string[] {
                            "Sauce Labs Bolt T-Shirt"});
                table1.AddRow(new string[] {
                            "Sauce Labs Fleece Jacket"});
                table1.AddRow(new string[] {
                            "Sauce Labs Onesie"});
#line 6
    await testRunner.AndAsync("I add the following 5 products to the cart and verify the button changes to \"Remo" +
                        "ve\":", ((string)(null)), table1, "And ");
#line hidden
#line 13
    await testRunner.AndAsync("I click on the shopping cart", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
    await testRunner.AndAsync("I click on the checkout button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
    await testRunner.AndAsync("I enter checkout information with first name \"John\", last name \"Doe\", and postal " +
                        "code \"12345\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
    await testRunner.AndAsync("I click continue to proceed to checkout overview", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "ProductName",
                            "Quantity",
                            "Description"});
                table2.AddRow(new string[] {
                            "Sauce Labs Backpack",
                            "1",
                            "carry.allTheThings() with the sleek, streamlined Sly Pack that melds uncompromisi" +
                                "ng style with unequaled laptop and tablet protection."});
                table2.AddRow(new string[] {
                            "Sauce Labs Bike Light",
                            "1",
                            "A red light isn\'t the desired state in testing but it sure helps when riding your" +
                                " bike at night. Water-resistant with 3 lighting modes, 1 AAA battery included."});
                table2.AddRow(new string[] {
                            "Sauce Labs Bolt T-Shirt",
                            "1",
                            "Get your testing superhero on with the Sauce Labs bolt T-shirt. From American App" +
                                "arel, 100% ringspun combed cotton, heather gray with red bolt."});
                table2.AddRow(new string[] {
                            "Sauce Labs Fleece Jacket",
                            "1",
                            "It\'s not every day that you come across a midweight quarter-zip fleece jacket cap" +
                                "able of handling everything from a relaxing day outdoors to a busy day at the of" +
                                "fice."});
                table2.AddRow(new string[] {
                            "Sauce Labs Onesie",
                            "1",
                            "Rib snap infant onesie for the junior automation engineer in development. Reinfor" +
                                "ced 3-snap bottom closure, two-needle hemmed sleeved and bottom won\'t unravel."});
#line 17
    await testRunner.ThenAsync("I verify the quantity and description for all added products:", ((string)(null)), table2, "Then ");
#line hidden
#line 24
    await testRunner.WhenAsync("I click on the finish button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
    await testRunner.AndAsync("I click on the back home button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
    await testRunner.ThenAsync("I should be navigated back to the inventory home page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
